import './globals.css';
import type { Metadata } from 'next';
import { Cabin } from 'next/font/google';
import Navbar from './components/Navbar';
import Footer from './components/Footer';

const cabin = Cabin({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={cabin.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
